# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-09 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightLog', '0005_auto_20170106_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedflight',
            name='gnd_activity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
